const Images = {
  logo: new URL("./goai-logo.png", import.meta.url).href,
  bannercircle: new URL("./banner-circle.webp", import.meta.url).href,
  heroimage: new URL("./hero-image.webp", import.meta.url).href,
  missionimage: new URL("./mission-image.webp", import.meta.url).href,
  missionbackground: new URL("./mission-background.webp", import.meta.url).href,
  orbit1: new URL("./orbit1.png", import.meta.url).href,
  orbit2: new URL("./orbit2.png", import.meta.url).href,
  orbit3: new URL("./orbit3.png", import.meta.url).href,
  orbit4: new URL("./orbit4.png", import.meta.url).href,
  ranks: new URL("./rank-image.webp", import.meta.url).href,
  smallicon1: new URL("./smallicon1.png", import.meta.url).href,
  smallicon2: new URL("./smallicon2.png", import.meta.url).href,
  smallicon3: new URL("./smallicon3.png", import.meta.url).href,
  smallicon4: new URL("./smallicon4.png", import.meta.url).href,
  smallicon5: new URL("./smallicon5.png", import.meta.url).href,
  smallicon6: new URL("./smallicon6.png", import.meta.url).href,
  smallicon7: new URL("./smallicon7.png", import.meta.url).href,
  smallicon8: new URL("./smallicon8.png", import.meta.url).href,
  smallicon9: new URL("./smallicon9.png", import.meta.url).href,
  smallicon10: new URL("./smallicon10.png", import.meta.url).href,
  smallicon11: new URL("./smallicon11.png", import.meta.url).href,
  smallicon12: new URL("./smallicon12.png", import.meta.url).href,
  Ecosystem1: new URL("./IMG1.png", import.meta.url).href,
  Ecosystem2: new URL("./IMG2.png", import.meta.url).href,
  Ecosystem3: new URL("./IMG3.png", import.meta.url).href,
  Ecosystem4: new URL("./IMG4.png", import.meta.url).href,
  icon1:new URL("./icon1.png",import.meta.url).href,
    icon2:new URL("./icon2.png",import.meta.url).href,
      icon3:new URL("./icon3.png",import.meta.url).href,
};
export default Images;
